module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      // width: {
      //   side: "25rem",
      // },
      minWidth: {
        96: "24rem",
        80: "20rem",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        qanelas: ["Qanelas", "sans-serif"],
        gilroy: ["Gilroy", "sans-serif"],
      },
      backgroundColor: theme => ({
        ...theme("colors"),
        nav: "#0F0023",
        hover: "#EC744F",
        primary: "#0a0028",
        crem: "#fcab63",
        customPink: "#FF5F7F",
        customError: "#DC3545",
        customSuccess: "#28a745",
        customArchive: "#EFE5E2",
        customArchiveItem: "#EBEAEA",
        customDropdownHead: "#f65c5c",
        customDropdown: "#F87171",
        customCrem: "#FCAB63",
        customCremOpacity: "#fdc899",
        customFirst: "#2641A1",
        customMiddle: "#FF5F7F",
        customSecond: "#FF5F80",
        customThird: "#FE8471",
        customLast: "#FCAB63",
        customBlueForum: "#3884FD",
        customGreyForum: "#F8F8F8",
      }),
      textColor: theme => theme("colors"),
      textColor: {
        // hover: "#EC744F",
        // primary: "#2E4553",
        bg: "#0a0028",
        primary: "#ff5f7f",
        secondary: "#2641a1",
        customArchive: "#374770",
        customWhite: "FFFFFF",
        customPink: "#FE6081",
        customCrem: "#fcab63",
        customGrey: "#EBEBEB",
        customFirst: "#2641A1",
        customSecond: "#FF5F80",
        customThird: "#FE8471",
        customLast: "#FCAB63",
        customBlueForum: "#3884FD",
      },
      borderColor: theme => ({
        ...theme("colors"),
        DEFAULT: theme("colors.gray.300", "currentColor"),
        primary: "#20639B",
        secondary: "0F0023",
        customGrey: "#AEA9A9",
      }),
      boxShadow: {
        lg: "0 0 4px 2px #20639b",
      },
      gradientColorStops: theme => ({
        ...theme("colors"),
        first: "#2641A1",
        second: "#FF5F80",
        middle: "#FF5F7F",
        third: "#FE8471",
        last: "#FCAB63",
      }),
      boxShadow: {
        white: "rgba(0, 0, 0, 0.2) 0px 18px 50px -10px",
        black:
          "rgba(16, 15, 16, 0.4) -5px 5px, rgba(16, 15, 16, 0.3) -10px 10px, rgba(16, 15, 16, 0.2) -15px 15px, rgba(16, 15, 16, 0.1) -20px 20px, rgba(16, 15, 16, 0.05) -25px 25px;",
      },
      backgroundImage: {
        komunitas: "url('/img/komunitas.png')",
        workshop: "url('/img/workshop.png')",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
